{% set name = "xcb-util" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://xcb.freedesktop.org/dist/xcb-util-{{ version }}.tar.bz2
  sha256: 46e49469cb3b594af1d33176cd7565def2be3fa8be4371d62271fabb5eae50e9

build:
  number: 2
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('xcb-util', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - libxcb
    - xorg-xproto

test:
  commands:
    - test -f ${PREFIX}/lib/libxcb-util.so

about:
  home: https://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Standard X key constants and conversion to/from keycodes'

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
