{% set name = "xcb-util" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://xcb.freedesktop.org/dist/xcb-util-{{ version }}.tar.xz
  sha256: 5abe3bbbd8e54f0fa3ec945291b7e8fa8cfd3cccc43718f8758430f94126e512

build:
  number: 2
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('xcb-util', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - libxcb
    - xorg-xproto

test:
  commands:
    - test -f ${PREFIX}/lib/libxcb-util.so

about:
  home: https://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Standard X key constants and conversion to/from keycodes'

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
